version: '3.1'
services:
  postgres:
    build: docker/postgres
    container_name: stat4market_postgres
    ports:
      - '65432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  php:
    build: docker/php-fpm
    container_name: stat4market_php
    environment:
      APP_ENV: dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./:/var/www/backend
      - ./docker/php-fpm/custom.conf:/usr/local/etc/php-fpm.d/custom.conf
      - ./docker/php-fpm/bashrc:/root/.bashrc
  nginx:
    build: docker/nginx
    container_name: stat4market_nginx
    restart: always
    ports:
      - '680:80'
      - '6443:443'
    volumes:
      - ./:/var/www/backend
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/hosts/stat4market_local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/stat4market.local:/etc/nginx/ssl
volumes:
  pgdata:
    driver: local